name: Flutter App Patcher 🚬

on:
  workflow_dispatch:

jobs:
  patch-it:
    runs-on: ubuntu-latest

    steps:
      - name: هێنانە ناوەوەی فایلەکانی ڕیپۆکە
        uses: actions/checkout@v4

      - name: دانانی پایتۆن بۆ ئامرازەکان
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: دانانی جاڤا بۆ واژۆکردن (Signing)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: دابەزاندنی بەرنامە پێویستەکان
        run: |
          pip install reflutter
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O signer.jar

      - name: داگرتنی ئەپەکە لە ڕیلیسەوە 🚬
        run: |
          echo "داگرتنی ئەپەکە..."
          wget -O app.apk "https://github.com/Skugiijb546vi/Chaqlyonetv/releases/download/V7/app.apk"

      - name: تێکشکاندنی سیکیوریتی فڵەتەر 🚬
        run: |
          echo -e "1\n127.0.0.1\n" | reflutter app.apk
          
      - name: پشکنینی ناوەکان (کێشەکە لێرە دەردەکەوێت) 🚬
        run: |
          echo "دوای تێکشکاندن، ئەم فایلانە لێرەن:"
          ls -lh *.apk
          
      - name: واژۆکردنەوەی ئەپەکە بۆ ئەوەی کڕاش نەکات
        run: |
          java -jar signer.jar -a *RE*.apk --allowResign -o final-output
          
      - name: بەرزکردنەوەی ئەپە ئامادەکراوەکە بۆ داگرتن
        uses: actions/upload-artifact@v4
        with:
          name: Patched-App-Ready
          path: final-output/*.apk
