name: Flutter App Patcher 🚬

on:
  workflow_dispatch:

jobs:
  patch-it:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: هێنانە ناوەوەی فایلەکان
        uses: actions/checkout@v4

      - name: دانانی پایتۆن و جاڤا
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: دابەزاندنی ئامرازەکان
        run: |
          pip install reflutter
          wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O signer.jar

      - name: داگرتنی ئەپەکە بە شێوەی سیستەمی 🚬
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "هێنانی فایلەکە لە ڕیلیسەوە..."
          # ئەم کۆدە خۆکارانە فایلی app.apk لە ڕیلیس ڕادەکێشێت بێ گوێدانە لینک
          gh release download --pattern 'app.apk'

      - name: تێکشکاندنی فڵەتەر 🚬
        run: |
          echo -e "1\n127.0.0.1\n" | reflutter app.apk
          
      - name: واژۆکردنەوەی ئەپەکە
        run: |
          java -jar signer.jar -a *RE*.apk --allowResign -o final-output
          
      - name: بەرزکردنەوەی ئەپە ئامادەکراوەکە
        uses: actions/upload-artifact@v4
        with:
          name: Patched-App-Ready
          path: final-output/*.apk
